dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.1

compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.1"

dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}
